import React, { useState } from 'react';
import { router } from '@inertiajs/react';
import AppShell from '@/Layouts/AppShell';
import { Badge } from '@/Components/UI/Badge';
import { Button } from '@/Components/UI/Button';
import { Card } from '@/Components/UI/Card';
import { Input } from '@/Components/UI/Input';
import { Select } from '@/Components/UI/Select';
import { SectionHeader } from '@/Components/UI/SectionHeader';

export default function Payments({ payments, projects = [], customers = [] }: any) {
  const records = payments?.data || payments || [];
  const [form, setForm] = useState({ project_id: '', customer_id: '', reference: '', payment_date: new Date().toISOString().slice(0, 10), amount: '', payment_method: 'bank', notes: '' });
  return <AppShell title="Project Payments" breadcrumbs={[{ label: 'Projects' }, { label: 'Project Payments' }]}><div className="space-y-6"><SectionHeader title="Project Payments" description="Create, submit, approve, reject, and settle customer project payments." badge={<Badge variant="purple" size="sm">{records.length} Payments</Badge>} />
    <Card level={0} className="p-5"><form onSubmit={e => { e.preventDefault(); router.post('/taskly/project-payments', form); }} className="grid sm:grid-cols-2 xl:grid-cols-4 gap-3"><Select label="Project" value={form.project_id} onChange={e => setForm({ ...form, project_id: e.target.value })} required><option value="">Select project</option>{projects.map((p: any) => <option key={p.id} value={p.id}>{p.name}</option>)}</Select><Select label="Customer" value={form.customer_id} onChange={e => setForm({ ...form, customer_id: e.target.value })}><option value="">No customer</option>{customers.map((c: any) => <option key={c.id} value={c.id}>{c.name}</option>)}</Select><Input label="Payment Date" type="date" value={form.payment_date} onChange={e => setForm({ ...form, payment_date: e.target.value })} required /><Input label="Amount" type="number" min="0.01" step="0.01" value={form.amount} onChange={e => setForm({ ...form, amount: e.target.value })} required /><Select label="Method" value={form.payment_method} onChange={e => setForm({ ...form, payment_method: e.target.value })}><option value="bank">Bank</option><option value="card">Card</option><option value="online">Online</option><option value="cash">Cash</option><option value="other">Other</option></Select><Input label="Reference" value={form.reference} onChange={e => setForm({ ...form, reference: e.target.value })} /><Input label="Notes" value={form.notes} onChange={e => setForm({ ...form, notes: e.target.value })} /><div className="flex items-end"><Button type="submit" variant="primary">Create Payment</Button></div></form></Card>
    <Card level={0} className="overflow-x-auto"><table className="w-full text-xs"><thead><tr className="text-left border-b border-[var(--border-subtle)]"><th className="p-3">Project</th><th>Customer</th><th>Date</th><th>Amount</th><th>Method</th><th>Reference</th><th>Status</th><th className="pr-3">Review</th></tr></thead><tbody>{records.map((record: any) => <tr key={record.id} className="border-b border-[var(--border-subtle)]"><td className="p-3">{record.project_name}</td><td>{record.customer_name || '—'}</td><td>{record.payment_date}</td><td>{Number(record.amount).toFixed(2)}</td><td>{record.payment_method}</td><td>{record.reference || '—'}</td><td><Badge size="sm" variant="neutral">{record.status}</Badge></td><td className="pr-3"><select className="input-shell" value={record.status} onChange={e => router.post(`/taskly/project-payments/${record.id}/review`, { status: e.target.value })}><option value="draft">Draft</option><option value="submitted">Submitted</option><option value="approved">Approved</option><option value="rejected">Rejected</option><option value="paid">Paid</option></select></td></tr>)}</tbody></table></Card>
  </div></AppShell>;
}
