import React, { useState } from 'react';
import { router } from '@inertiajs/react';
import AppShell from '@/Layouts/AppShell';
import { Button } from '@/Components/UI/Button';
import { Card } from '@/Components/UI/Card';
import { Input } from '@/Components/UI/Input';
import { SectionHeader } from '@/Components/UI/SectionHeader';

export default function Setup({ statuses = [], stageTemplates = [] }: any) {
  const [status, setStatus] = useState({ name: '', color: '#64748b', is_closed: false, position: 0 });
  const [stage, setStage] = useState({ name: '', is_complete: false, position: 0 });
  return <AppShell title="Project System Setup" breadcrumbs={[{ label: 'Projects' }, { label: 'System Setup' }]}><div className="space-y-6"><SectionHeader title="Project System Setup" description="Maintain reusable project statuses and task-stage templates equivalent to WorkDo setup lists." /><div className="grid xl:grid-cols-2 gap-5"><SetupCard title="Project Statuses" records={statuses}><form onSubmit={e => { e.preventDefault(); router.post('/taskly/setup/project-statuses', status); }} className="grid sm:grid-cols-2 gap-3"><Input label="Name" value={status.name} onChange={e => setStatus({ ...status, name: e.target.value })} required /><Input label="Color" type="color" value={status.color} onChange={e => setStatus({ ...status, color: e.target.value })} /><Input label="Position" type="number" min="0" value={status.position} onChange={e => setStatus({ ...status, position: Number(e.target.value) })} /><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={status.is_closed} onChange={e => setStatus({ ...status, is_closed: e.target.checked })} /> Closed status</label><Button type="submit" variant="primary">Save Status</Button></form></SetupCard><SetupCard title="Task Stage Templates" records={stageTemplates}><form onSubmit={e => { e.preventDefault(); router.post('/taskly/setup/stage-templates', stage); }} className="grid sm:grid-cols-2 gap-3"><Input label="Name" value={stage.name} onChange={e => setStage({ ...stage, name: e.target.value })} required /><Input label="Position" type="number" min="0" value={stage.position} onChange={e => setStage({ ...stage, position: Number(e.target.value) })} /><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={stage.is_complete} onChange={e => setStage({ ...stage, is_complete: e.target.checked })} /> Completion stage</label><Button type="submit" variant="primary">Save Stage</Button></form></SetupCard></div></div></AppShell>;
}
function SetupCard({ title, records, children }: any) { return <Card level={0} className="p-5 space-y-5"><h3 className="font-bold">{title}</h3>{children}<div className="space-y-2">{records.map((record: any) => <div key={record.id} className="flex items-center justify-between p-3 rounded-xl border border-[var(--border-subtle)]"><span>{record.name}</span><span className="text-xs text-[var(--text-tertiary)]">#{record.position} {record.is_closed || record.is_complete ? '• Complete' : ''}</span></div>)}</div></Card>; }
