import React from 'react';
import { router } from '@inertiajs/react';
import { Button } from '@/Components/UI/Button';
import { Card } from '@/Components/UI/Card';
import { Plus, Save, Upload } from 'lucide-react';

interface Props {
  module: string;
  section: string;
  canManage: boolean;
  lookups: any;
}

const inputClass = 'w-full px-3 py-2 rounded-xl bg-[var(--surface-2)] border border-[var(--border-subtle)] text-sm outline-none focus:border-purple-500/50';

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return <label className="space-y-1"><span className="block text-[11px] font-semibold text-[var(--text-secondary)]">{label}</span>{children}</label>;
}

function Panel({ title, children }: { title: string; children: React.ReactNode }) {
  const [open, setOpen] = React.useState(false);
  return (
    <Card level={0} className="space-y-4">
      <div className="flex items-center justify-between gap-3">
        <div><h3 className="text-sm font-bold">{title}</h3><p className="text-[11px] text-[var(--text-tertiary)]">Uses the existing governed business action.</p></div>
        <Button type="button" variant={open ? 'outline' : 'primary'} size="sm" icon={<Plus className="w-3.5 h-3.5" />} onClick={() => setOpen(v => !v)}>{open ? 'Close' : 'New'}</Button>
      </div>
      {open ? children : null}
    </Card>
  );
}

function submit(path: string, data: any, reset?: () => void) {
  router.post(path, data, { preserveScroll: true, onSuccess: () => reset?.() });
}

function CrmActions({ section, lookups }: Pick<Props, 'section' | 'lookups'>) {
  const pipelines = lookups?.pipelines || [];
  const members = lookups?.members || [];
  const leads = lookups?.leads || [];
  const deals = lookups?.deals || [];

  if (section === 'pipelines') {
    return <Panel title="Create Pipeline"><PipelineForm /></Panel>;
  }
  if (section === 'leads') {
    return <div className="grid grid-cols-1 xl:grid-cols-2 gap-4"><Panel title="Create Lead"><LeadForm pipelines={pipelines} members={members} /></Panel><Panel title="Convert Lead to Deal"><ConvertLeadForm leads={leads} /></Panel></div>;
  }
  if (section === 'webforms') {
    return <Panel title="Create Lead Capture Form"><WebformForm pipelines={pipelines} members={members} /></Panel>;
  }
  if (section === 'activities') {
    return <Panel title="Add CRM Activity"><SubjectActionForm kind="activity" leads={leads} deals={deals} members={members} /></Panel>;
  }
  if (section === 'notes') {
    return <Panel title="Add CRM Note"><SubjectActionForm kind="note" leads={leads} deals={deals} members={members} /></Panel>;
  }
  return null;
}

function PipelineForm() {
  const [name, setName] = React.useState('');
  const [stages, setStages] = React.useState('New, Qualified, Proposal, Negotiation');
  const [isDefault, setDefault] = React.useState(false);
  return <form onSubmit={(e) => { e.preventDefault(); const parsed = stages.split(',').map(s => s.trim()).filter(Boolean).map((stage, i) => ({ name: stage, probability: Math.min(90, i * 20), is_closed: false })); submit('/crm/pipelines', { name, is_default: isDefault, stages: parsed }, () => setName('')); }} className="grid grid-cols-1 md:grid-cols-3 gap-3"><Field label="Pipeline Name"><input className={inputClass} value={name} onChange={e => setName(e.target.value)} required /></Field><Field label="Stages (comma separated)"><input className={inputClass} value={stages} onChange={e => setStages(e.target.value)} required /></Field><label className="flex items-end gap-2 pb-2 text-xs"><input type="checkbox" checked={isDefault} onChange={e => setDefault(e.target.checked)} /> Default pipeline</label><div className="md:col-span-3 flex justify-end"><Button type="submit" variant="primary" icon={<Save className="w-3.5 h-3.5" />}>Create Pipeline</Button></div></form>;
}

function LeadForm({ pipelines, members }: any) {
  const firstPipeline = pipelines[0];
  const [data, setData] = React.useState<any>({ pipeline_id: firstPipeline?.id || '', stage_id: firstPipeline?.stages?.[0]?.id || '', name: '', email: '', phone: '', company: '', estimated_value: 0, assigned_to: '' });
  const pipeline = pipelines.find((p: any) => Number(p.id) === Number(data.pipeline_id));
  const updatePipeline = (id: string) => { const selected = pipelines.find((p: any) => Number(p.id) === Number(id)); setData({ ...data, pipeline_id: id, stage_id: selected?.stages?.[0]?.id || '' }); };
  return <form onSubmit={e => { e.preventDefault(); submit('/crm/leads', { ...data, assigned_to: data.assigned_to || null }, () => setData({ ...data, name: '', email: '', phone: '', company: '', estimated_value: 0 })); }} className="grid grid-cols-1 md:grid-cols-2 gap-3"><Field label="Name"><input className={inputClass} value={data.name} onChange={e => setData({...data,name:e.target.value})} required /></Field><Field label="Company"><input className={inputClass} value={data.company} onChange={e => setData({...data,company:e.target.value})} /></Field><Field label="Email"><input type="email" className={inputClass} value={data.email} onChange={e => setData({...data,email:e.target.value})} /></Field><Field label="Phone"><input className={inputClass} value={data.phone} onChange={e => setData({...data,phone:e.target.value})} /></Field><Field label="Pipeline"><select className={inputClass} value={data.pipeline_id} onChange={e => updatePipeline(e.target.value)} required><option value="">Select</option>{pipelines.map((p:any)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Stage"><select className={inputClass} value={data.stage_id} onChange={e => setData({...data,stage_id:e.target.value})} required><option value="">Select</option>{(pipeline?.stages||[]).map((s:any)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><Field label="Estimated Value"><input type="number" min="0" step="0.01" className={inputClass} value={data.estimated_value} onChange={e => setData({...data,estimated_value:Number(e.target.value)})} /></Field><Field label="Assignee"><select className={inputClass} value={data.assigned_to} onChange={e => setData({...data,assigned_to:e.target.value})}><option value="">Unassigned</option>{members.map((m:any)=><option key={m.id} value={m.id}>{m.name}</option>)}</select></Field><div className="md:col-span-2 flex justify-end"><Button type="submit" variant="primary">Create Lead</Button></div></form>;
}

function ConvertLeadForm({ leads }: any) {
  const [data, setData] = React.useState<any>({ lead_id: '', name: '', value: 0, expected_close_on: '', create_customer: true });
  return <form onSubmit={e => { e.preventDefault(); if (!data.lead_id) return; submit(`/crm/leads/${data.lead_id}/convert`, { name:data.name||null, value:data.value||null, expected_close_on:data.expected_close_on||null, create_customer:data.create_customer }); }} className="grid grid-cols-1 md:grid-cols-2 gap-3"><Field label="Lead"><select className={inputClass} value={data.lead_id} onChange={e=>setData({...data,lead_id:e.target.value})} required><option value="">Select lead</option>{leads.filter((l:any)=>l.status==='open').map((l:any)=><option key={l.id} value={l.id}>{l.name}</option>)}</select></Field><Field label="Deal Name"><input className={inputClass} value={data.name} onChange={e=>setData({...data,name:e.target.value})} /></Field><Field label="Value"><input type="number" min="0" step="0.01" className={inputClass} value={data.value} onChange={e=>setData({...data,value:Number(e.target.value)})} /></Field><Field label="Expected Close"><input type="date" className={inputClass} value={data.expected_close_on} onChange={e=>setData({...data,expected_close_on:e.target.value})} /></Field><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={data.create_customer} onChange={e=>setData({...data,create_customer:e.target.checked})} /> Create customer record</label><div className="md:col-span-2 flex justify-end"><Button type="submit" variant="primary">Convert Lead</Button></div></form>;
}

function WebformForm({ pipelines, members }: any) {
  const first = pipelines[0];
  const [data,setData] = React.useState<any>({name:'',pipeline_id:first?.id||'',stage_id:first?.stages?.[0]?.id||'',assigned_to:''});
  const pipeline = pipelines.find((p:any)=>Number(p.id)===Number(data.pipeline_id));
  return <form onSubmit={e=>{e.preventDefault();submit('/crm/webforms',{...data,assigned_to:data.assigned_to||null,fields:['name','email','phone','company','message']},()=>setData({...data,name:''}));}} className="grid grid-cols-1 md:grid-cols-2 gap-3"><Field label="Form Name"><input className={inputClass} value={data.name} onChange={e=>setData({...data,name:e.target.value})} required /></Field><Field label="Pipeline"><select className={inputClass} value={data.pipeline_id} onChange={e=>{const p=pipelines.find((x:any)=>Number(x.id)===Number(e.target.value));setData({...data,pipeline_id:e.target.value,stage_id:p?.stages?.[0]?.id||''});}} required>{pipelines.map((p:any)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Default Stage"><select className={inputClass} value={data.stage_id} onChange={e=>setData({...data,stage_id:e.target.value})} required>{(pipeline?.stages||[]).map((s:any)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><Field label="Assignee"><select className={inputClass} value={data.assigned_to} onChange={e=>setData({...data,assigned_to:e.target.value})}><option value="">Unassigned</option>{members.map((m:any)=><option key={m.id} value={m.id}>{m.name}</option>)}</select></Field><div className="md:col-span-2 flex justify-end"><Button type="submit" variant="primary">Create Web Form</Button></div></form>;
}

function SubjectActionForm({ kind, leads, deals, members }: any) {
  const [data,setData] = React.useState<any>({subject_type:'lead',subject_id:'',body:'',activity_type:'call',title:'',due_at:'',assigned_to:''});
  const subjects = data.subject_type==='lead'?leads:deals;
  const send = (e:React.FormEvent)=>{e.preventDefault(); if(!data.subject_id)return; const path=`/crm/${data.subject_type}/${data.subject_id}/${kind==='note'?'notes':'activities'}`; const payload=kind==='note'?{body:data.body}:{type:data.activity_type,title:data.title,due_at:data.due_at||null,assigned_to:data.assigned_to||null}; submit(path,payload);};
  return <form onSubmit={send} className="grid grid-cols-1 md:grid-cols-2 gap-3"><Field label="Record Type"><select className={inputClass} value={data.subject_type} onChange={e=>setData({...data,subject_type:e.target.value,subject_id:''})}><option value="lead">Lead</option><option value="deal">Deal</option></select></Field><Field label="Record"><select className={inputClass} value={data.subject_id} onChange={e=>setData({...data,subject_id:e.target.value})} required><option value="">Select</option>{subjects.map((s:any)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field>{kind==='note'?<Field label="Note"><textarea className={inputClass} rows={3} value={data.body} onChange={e=>setData({...data,body:e.target.value})} required /></Field>:<><Field label="Activity Type"><select className={inputClass} value={data.activity_type} onChange={e=>setData({...data,activity_type:e.target.value})}><option>call</option><option>meeting</option><option>email</option><option>task</option></select></Field><Field label="Title"><input className={inputClass} value={data.title} onChange={e=>setData({...data,title:e.target.value})} required /></Field><Field label="Due"><input type="datetime-local" className={inputClass} value={data.due_at} onChange={e=>setData({...data,due_at:e.target.value})} /></Field><Field label="Assignee"><select className={inputClass} value={data.assigned_to} onChange={e=>setData({...data,assigned_to:e.target.value})}><option value="">Unassigned</option>{members.map((m:any)=><option key={m.id} value={m.id}>{m.name}</option>)}</select></Field></>}<div className="md:col-span-2 flex justify-end"><Button type="submit" variant="primary">Save {kind==='note'?'Note':'Activity'}</Button></div></form>;
}

function HrmActions({ section, lookups }: Pick<Props, 'section'|'lookups'>) {
  const employees=lookups?.employees||[]; const leaveTypes=lookups?.leaveTypes||[];
  const simpleStructure:Record<string,string>={branches:'branches',departments:'departments',designations:'designations',shifts:'shifts',holidays:'holidays'};
  if(simpleStructure[section]) return <Panel title={`Create ${section.replaceAll('-',' ')}`}><HrmStructureForm resource={simpleStructure[section]} lookups={lookups}/></Panel>;
  if(section==='employees') return <Panel title="Create Employee"><EmployeeForm lookups={lookups}/></Panel>;
  if(section==='attendance') return <Panel title="Record Attendance"><AttendanceForm employees={employees}/></Panel>;
  if(section==='leave-types') return <Panel title="Create Leave Type"><LeaveTypeForm/></Panel>;
  if(section==='leave-requests') return <Panel title="Request Leave"><LeaveForm employees={employees} leaveTypes={leaveTypes}/></Panel>;
  if(section==='salary-components') return <Panel title="Create Salary Component"><SalaryComponentForm/></Panel>;
  if(section==='payroll') return <Panel title="Generate Payslip"><PayslipForm employees={employees}/></Panel>;
  if(section==='appraisals') return <Panel title="Record Appraisal"><AppraisalForm employees={employees}/></Panel>;
  if(section==='documents') return <Panel title="Upload Employee Document"><DocumentForm employees={employees}/></Panel>;
  return null;
}

function HrmStructureForm({resource,lookups}:any){const [d,setD]=React.useState<any>({name:'',branch_id:'',department_id:'',starts_at:'09:00',ends_at:'17:00',grace_minutes:10,holiday_date:'',is_optional:false});return <form onSubmit={e=>{e.preventDefault();const payload:any={name:d.name};if(resource==='departments')payload.branch_id=d.branch_id||null;if(resource==='designations')payload.department_id=d.department_id||null;if(resource==='shifts')Object.assign(payload,{starts_at:d.starts_at,ends_at:d.ends_at,grace_minutes:d.grace_minutes});if(resource==='holidays')Object.assign(payload,{holiday_date:d.holiday_date,is_optional:d.is_optional});submit(`/hrm/structure/${resource}`,payload,()=>setD({...d,name:''}));}} className="grid grid-cols-1 md:grid-cols-2 gap-3"><Field label="Name"><input className={inputClass} value={d.name} onChange={e=>setD({...d,name:e.target.value})} required/></Field>{resource==='departments'&&<Field label="Branch"><select className={inputClass} value={d.branch_id} onChange={e=>setD({...d,branch_id:e.target.value})}><option value="">None</option>{(lookups.branches||[]).map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field>}{resource==='designations'&&<Field label="Department"><select className={inputClass} value={d.department_id} onChange={e=>setD({...d,department_id:e.target.value})}><option value="">None</option>{(lookups.departments||[]).map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field>}{resource==='shifts'&&<><Field label="Start"><input type="time" className={inputClass} value={d.starts_at} onChange={e=>setD({...d,starts_at:e.target.value})}/></Field><Field label="End"><input type="time" className={inputClass} value={d.ends_at} onChange={e=>setD({...d,ends_at:e.target.value})}/></Field><Field label="Grace Minutes"><input type="number" min="0" className={inputClass} value={d.grace_minutes} onChange={e=>setD({...d,grace_minutes:Number(e.target.value)})}/></Field></>}{resource==='holidays'&&<><Field label="Date"><input type="date" className={inputClass} value={d.holiday_date} onChange={e=>setD({...d,holiday_date:e.target.value})} required/></Field><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={d.is_optional} onChange={e=>setD({...d,is_optional:e.target.checked})}/> Optional holiday</label></>}<div className="md:col-span-2 flex justify-end"><Button type="submit" variant="primary">Save</Button></div></form>}

function EmployeeForm({lookups}:any){const [d,setD]=React.useState<any>({employee_number:'',name:'',email:'',joined_at:'',basic_salary:0,branch_id:'',department_id:'',designation_id:'',shift_id:''});return <form onSubmit={e=>{e.preventDefault();submit('/hrm/employees',Object.fromEntries(Object.entries(d).map(([k,v])=>[k,v===''?null:v])),()=>setD({...d,employee_number:'',name:'',email:''}));}} className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-3"><Field label="Employee #"><input className={inputClass} value={d.employee_number} onChange={e=>setD({...d,employee_number:e.target.value})} required/></Field><Field label="Name"><input className={inputClass} value={d.name} onChange={e=>setD({...d,name:e.target.value})} required/></Field><Field label="Email"><input type="email" className={inputClass} value={d.email} onChange={e=>setD({...d,email:e.target.value})}/></Field><Field label="Joined"><input type="date" className={inputClass} value={d.joined_at} onChange={e=>setD({...d,joined_at:e.target.value})} required/></Field><Field label="Basic Salary"><input type="number" min="0" className={inputClass} value={d.basic_salary} onChange={e=>setD({...d,basic_salary:Number(e.target.value)})} required/></Field>{[['branch_id','Branch','branches'],['department_id','Department','departments'],['designation_id','Designation','designations'],['shift_id','Shift','shifts']].map(([key,label,list])=><Field key={key} label={label}><select className={inputClass} value={d[key]} onChange={e=>setD({...d,[key]:e.target.value})}><option value="">None</option>{(lookups[list]||[]).map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field>)}<div className="xl:col-span-4 flex justify-end"><Button type="submit" variant="primary">Create Employee</Button></div></form>}

function AttendanceForm({employees}:any){const [d,setD]=React.useState<any>({employee_id:'',attendance_date:new Date().toISOString().slice(0,10),clock_in:'',clock_out:'',status:'present',notes:''});return <form onSubmit={e=>{e.preventDefault();submit('/hrm/attendance',{...d,clock_in:d.clock_in||null,clock_out:d.clock_out||null});}} className="grid grid-cols-1 md:grid-cols-3 gap-3"><Field label="Employee"><select className={inputClass} value={d.employee_id} onChange={e=>setD({...d,employee_id:e.target.value})} required><option value="">Select</option>{employees.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Date"><input type="date" className={inputClass} value={d.attendance_date} onChange={e=>setD({...d,attendance_date:e.target.value})} required/></Field><Field label="Status"><select className={inputClass} value={d.status} onChange={e=>setD({...d,status:e.target.value})}>{['present','absent','late','half_day','remote'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Clock In"><input type="datetime-local" className={inputClass} value={d.clock_in} onChange={e=>setD({...d,clock_in:e.target.value})}/></Field><Field label="Clock Out"><input type="datetime-local" className={inputClass} value={d.clock_out} onChange={e=>setD({...d,clock_out:e.target.value})}/></Field><Field label="Notes"><input className={inputClass} value={d.notes} onChange={e=>setD({...d,notes:e.target.value})}/></Field><div className="md:col-span-3 flex justify-end"><Button type="submit" variant="primary">Record</Button></div></form>}

function LeaveTypeForm(){const[d,setD]=React.useState<any>({name:'',annual_allowance:12,is_paid:true});return <form onSubmit={e=>{e.preventDefault();submit('/hrm/leave-types',d,()=>setD({...d,name:''}));}} className="grid grid-cols-1 md:grid-cols-3 gap-3"><Field label="Name"><input className={inputClass} value={d.name} onChange={e=>setD({...d,name:e.target.value})} required/></Field><Field label="Annual Allowance"><input type="number" min="0" className={inputClass} value={d.annual_allowance} onChange={e=>setD({...d,annual_allowance:Number(e.target.value)})} required/></Field><label className="flex items-end gap-2 pb-2 text-xs"><input type="checkbox" checked={d.is_paid} onChange={e=>setD({...d,is_paid:e.target.checked})}/> Paid leave</label><div className="md:col-span-3 flex justify-end"><Button type="submit" variant="primary">Save</Button></div></form>}

function LeaveForm({employees,leaveTypes}:any){const[d,setD]=React.useState<any>({employee_id:'',leave_type_id:'',starts_on:'',ends_on:'',reason:''});return <form onSubmit={e=>{e.preventDefault();submit('/hrm/leaves',d);}} className="grid grid-cols-1 md:grid-cols-2 gap-3"><Field label="Employee"><select className={inputClass} value={d.employee_id} onChange={e=>setD({...d,employee_id:e.target.value})} required><option value="">Select</option>{employees.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Leave Type"><select className={inputClass} value={d.leave_type_id} onChange={e=>setD({...d,leave_type_id:e.target.value})} required><option value="">Select</option>{leaveTypes.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Starts"><input type="date" className={inputClass} value={d.starts_on} onChange={e=>setD({...d,starts_on:e.target.value})} required/></Field><Field label="Ends"><input type="date" className={inputClass} value={d.ends_on} onChange={e=>setD({...d,ends_on:e.target.value})} required/></Field><Field label="Reason"><textarea className={inputClass} value={d.reason} onChange={e=>setD({...d,reason:e.target.value})}/></Field><div className="md:col-span-2 flex justify-end"><Button type="submit" variant="primary">Submit Leave</Button></div></form>}

function SalaryComponentForm(){const[d,setD]=React.useState<any>({name:'',type:'earning',calculation:'fixed',value:0,is_taxable:false});return <form onSubmit={e=>{e.preventDefault();submit('/hrm/salary-components',d,()=>setD({...d,name:''}));}} className="grid grid-cols-1 md:grid-cols-4 gap-3"><Field label="Name"><input className={inputClass} value={d.name} onChange={e=>setD({...d,name:e.target.value})} required/></Field><Field label="Type"><select className={inputClass} value={d.type} onChange={e=>setD({...d,type:e.target.value})}><option>earning</option><option>deduction</option></select></Field><Field label="Calculation"><select className={inputClass} value={d.calculation} onChange={e=>setD({...d,calculation:e.target.value})}><option>fixed</option><option>percentage</option></select></Field><Field label="Value"><input type="number" min="0" step="0.01" className={inputClass} value={d.value} onChange={e=>setD({...d,value:Number(e.target.value)})}/></Field><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={d.is_taxable} onChange={e=>setD({...d,is_taxable:e.target.checked})}/> Taxable</label><div className="md:col-span-4 flex justify-end"><Button type="submit" variant="primary">Save Component</Button></div></form>}

function PayslipForm({employees}:any){const[d,setD]=React.useState<any>({employee_id:'',period_start:'',period_end:''});return <form onSubmit={e=>{e.preventDefault();submit('/hrm/payslips',d);}} className="grid grid-cols-1 md:grid-cols-3 gap-3"><Field label="Employee"><select className={inputClass} value={d.employee_id} onChange={e=>setD({...d,employee_id:e.target.value})} required><option value="">Select</option>{employees.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Period Start"><input type="date" className={inputClass} value={d.period_start} onChange={e=>setD({...d,period_start:e.target.value})} required/></Field><Field label="Period End"><input type="date" className={inputClass} value={d.period_end} onChange={e=>setD({...d,period_end:e.target.value})} required/></Field><div className="md:col-span-3 flex justify-end"><Button type="submit" variant="primary">Generate Payslip</Button></div></form>}

function AppraisalForm({employees}:any){const[d,setD]=React.useState<any>({employee_id:'',review_date:new Date().toISOString().slice(0,10),rating:3,feedback:''});return <form onSubmit={e=>{e.preventDefault();submit('/hrm/appraisals',d);}} className="grid grid-cols-1 md:grid-cols-3 gap-3"><Field label="Employee"><select className={inputClass} value={d.employee_id} onChange={e=>setD({...d,employee_id:e.target.value})} required><option value="">Select</option>{employees.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Review Date"><input type="date" className={inputClass} value={d.review_date} onChange={e=>setD({...d,review_date:e.target.value})} required/></Field><Field label="Rating"><select className={inputClass} value={d.rating} onChange={e=>setD({...d,rating:Number(e.target.value)})}>{[1,2,3,4,5].map(x=><option key={x} value={x}>{x}/5</option>)}</select></Field><Field label="Feedback"><textarea className={inputClass} value={d.feedback} onChange={e=>setD({...d,feedback:e.target.value})}/></Field><div className="md:col-span-3 flex justify-end"><Button type="submit" variant="primary">Save Appraisal</Button></div></form>}

function DocumentForm({employees}:any){const[employee,setEmployee]=React.useState('');const[name,setName]=React.useState('');const[expires,setExpires]=React.useState('');const[file,setFile]=React.useState<File|null>(null);return <form onSubmit={e=>{e.preventDefault();if(!file)return;const fd=new FormData();fd.append('employee_id',employee);fd.append('name',name);fd.append('file',file);if(expires)fd.append('expires_on',expires);router.post('/hrm/documents',fd,{forceFormData:true,preserveScroll:true});}} className="grid grid-cols-1 md:grid-cols-4 gap-3"><Field label="Employee"><select className={inputClass} value={employee} onChange={e=>setEmployee(e.target.value)} required><option value="">Select</option>{employees.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Document Name"><input className={inputClass} value={name} onChange={e=>setName(e.target.value)} required/></Field><Field label="Expires On"><input type="date" className={inputClass} value={expires} onChange={e=>setExpires(e.target.value)}/></Field><Field label="File"><input type="file" className={inputClass} onChange={e=>setFile(e.target.files?.[0]||null)} required/></Field><div className="md:col-span-4 flex justify-end"><Button type="submit" variant="primary" icon={<Upload className="w-3.5 h-3.5"/>}>Upload</Button></div></form>}

function TasklyActions({section,lookups}:Pick<Props,'section'|'lookups'>){const projects=lookups?.projects||[];const tasks=lookups?.tasks||[];const members=lookups?.members||[];if(section==='projects')return <Panel title="Create Project"><ProjectForm members={members}/></Panel>;if(section==='tasks')return <Panel title="Create Task"><TaskForm projects={projects} members={members}/></Panel>;if(section==='milestones')return <Panel title="Create Milestone"><MilestoneForm projects={projects}/></Panel>;if(section==='timesheets')return <Panel title="Submit Timesheet"><TimesheetForm projects={projects} tasks={tasks} members={members}/></Panel>;if(section==='issues')return <Panel title="Report Issue"><IssueForm projects={projects} tasks={tasks} members={members}/></Panel>;return null;}

function ProjectForm({members}:any){const[d,setD]=React.useState<any>({name:'',description:'',starts_on:'',due_on:'',budget:0,manager_id:''});return <form onSubmit={e=>{e.preventDefault();submit('/taskly/projects',{...d,manager_id:d.manager_id||null,members:[],stages:[{name:'To Do',is_complete:false},{name:'In Progress',is_complete:false},{name:'Done',is_complete:true}]},()=>setD({...d,name:'',description:''}));}} className="grid grid-cols-1 md:grid-cols-3 gap-3"><Field label="Project Name"><input className={inputClass} value={d.name} onChange={e=>setD({...d,name:e.target.value})} required/></Field><Field label="Manager"><select className={inputClass} value={d.manager_id} onChange={e=>setD({...d,manager_id:e.target.value})}><option value="">None</option>{members.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Budget"><input type="number" min="0" step="0.01" className={inputClass} value={d.budget} onChange={e=>setD({...d,budget:Number(e.target.value)})}/></Field><Field label="Starts"><input type="date" className={inputClass} value={d.starts_on} onChange={e=>setD({...d,starts_on:e.target.value})}/></Field><Field label="Due"><input type="date" className={inputClass} value={d.due_on} onChange={e=>setD({...d,due_on:e.target.value})}/></Field><Field label="Description"><input className={inputClass} value={d.description} onChange={e=>setD({...d,description:e.target.value})}/></Field><div className="md:col-span-3 text-[10px] text-[var(--text-tertiary)]">Default stages: To Do → In Progress → Done. Stages can be managed through the existing project workflow.</div><div className="md:col-span-3 flex justify-end"><Button type="submit" variant="primary">Create Project</Button></div></form>}

function TaskForm({projects,members}:any){const[d,setD]=React.useState<any>({project_id:'',stage_id:'',assigned_to:'',title:'',description:'',priority:'medium',due_on:'',estimated_hours:0});const p=projects.find((x:any)=>Number(x.id)===Number(d.project_id));return <form onSubmit={e=>{e.preventDefault();submit('/taskly/tasks',{...d,assigned_to:d.assigned_to||null,due_on:d.due_on||null});}} className="grid grid-cols-1 md:grid-cols-3 gap-3"><Field label="Project"><select className={inputClass} value={d.project_id} onChange={e=>{const project=projects.find((x:any)=>Number(x.id)===Number(e.target.value));setD({...d,project_id:e.target.value,stage_id:project?.stages?.[0]?.id||''});}} required><option value="">Select</option>{projects.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Stage"><select className={inputClass} value={d.stage_id} onChange={e=>setD({...d,stage_id:e.target.value})} required><option value="">Select</option>{(p?.stages||[]).map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Assignee"><select className={inputClass} value={d.assigned_to} onChange={e=>setD({...d,assigned_to:e.target.value})}><option value="">Unassigned</option>{members.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Title"><input className={inputClass} value={d.title} onChange={e=>setD({...d,title:e.target.value})} required/></Field><Field label="Priority"><select className={inputClass} value={d.priority} onChange={e=>setD({...d,priority:e.target.value})}>{['low','medium','high','critical'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Due"><input type="date" className={inputClass} value={d.due_on} onChange={e=>setD({...d,due_on:e.target.value})}/></Field><Field label="Estimated Hours"><input type="number" min="0" step="0.25" className={inputClass} value={d.estimated_hours} onChange={e=>setD({...d,estimated_hours:Number(e.target.value)})}/></Field><Field label="Description"><input className={inputClass} value={d.description} onChange={e=>setD({...d,description:e.target.value})}/></Field><div className="md:col-span-3 flex justify-end"><Button type="submit" variant="primary">Create Task</Button></div></form>}

function MilestoneForm({projects}:any){const[d,setD]=React.useState<any>({project_id:'',name:'',due_on:''});return <form onSubmit={e=>{e.preventDefault();submit('/taskly/milestones',d,()=>setD({...d,name:''}));}} className="grid grid-cols-1 md:grid-cols-3 gap-3"><Field label="Project"><select className={inputClass} value={d.project_id} onChange={e=>setD({...d,project_id:e.target.value})} required><option value="">Select</option>{projects.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Name"><input className={inputClass} value={d.name} onChange={e=>setD({...d,name:e.target.value})} required/></Field><Field label="Due"><input type="date" className={inputClass} value={d.due_on} onChange={e=>setD({...d,due_on:e.target.value})}/></Field><div className="md:col-span-3 flex justify-end"><Button type="submit" variant="primary">Create Milestone</Button></div></form>}

function TimesheetForm({projects,tasks,members}:any){const[d,setD]=React.useState<any>({project_id:'',task_id:'',user_id:'',work_date:new Date().toISOString().slice(0,10),hours:1,description:''});const projectTasks=tasks.filter((x:any)=>Number(x.project_id)===Number(d.project_id));return <form onSubmit={e=>{e.preventDefault();submit('/taskly/timesheets',{...d,task_id:d.task_id||null});}} className="grid grid-cols-1 md:grid-cols-3 gap-3"><Field label="Project"><select className={inputClass} value={d.project_id} onChange={e=>setD({...d,project_id:e.target.value,task_id:''})} required><option value="">Select</option>{projects.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Task"><select className={inputClass} value={d.task_id} onChange={e=>setD({...d,task_id:e.target.value})}><option value="">None</option>{projectTasks.map((x:any)=><option key={x.id} value={x.id}>{x.title}</option>)}</select></Field><Field label="User"><select className={inputClass} value={d.user_id} onChange={e=>setD({...d,user_id:e.target.value})} required><option value="">Select</option>{members.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Date"><input type="date" className={inputClass} value={d.work_date} onChange={e=>setD({...d,work_date:e.target.value})} required/></Field><Field label="Hours"><input type="number" min="0.25" max="24" step="0.25" className={inputClass} value={d.hours} onChange={e=>setD({...d,hours:Number(e.target.value)})} required/></Field><Field label="Description"><input className={inputClass} value={d.description} onChange={e=>setD({...d,description:e.target.value})}/></Field><div className="md:col-span-3 flex justify-end"><Button type="submit" variant="primary">Submit Time</Button></div></form>}

function IssueForm({projects,tasks,members}:any){const[d,setD]=React.useState<any>({project_id:'',task_id:'',title:'',description:'',severity:'medium',assigned_to:''});const projectTasks=tasks.filter((x:any)=>Number(x.project_id)===Number(d.project_id));return <form onSubmit={e=>{e.preventDefault();submit('/taskly/issues',{...d,task_id:d.task_id||null,assigned_to:d.assigned_to||null});}} className="grid grid-cols-1 md:grid-cols-3 gap-3"><Field label="Project"><select className={inputClass} value={d.project_id} onChange={e=>setD({...d,project_id:e.target.value,task_id:''})} required><option value="">Select</option>{projects.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Task"><select className={inputClass} value={d.task_id} onChange={e=>setD({...d,task_id:e.target.value})}><option value="">None</option>{projectTasks.map((x:any)=><option key={x.id} value={x.id}>{x.title}</option>)}</select></Field><Field label="Severity"><select className={inputClass} value={d.severity} onChange={e=>setD({...d,severity:e.target.value})}>{['low','medium','high','critical'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Title"><input className={inputClass} value={d.title} onChange={e=>setD({...d,title:e.target.value})} required/></Field><Field label="Assignee"><select className={inputClass} value={d.assigned_to} onChange={e=>setD({...d,assigned_to:e.target.value})}><option value="">Unassigned</option>{members.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Description"><input className={inputClass} value={d.description} onChange={e=>setD({...d,description:e.target.value})}/></Field><div className="md:col-span-3 flex justify-end"><Button type="submit" variant="primary">Report Issue</Button></div></form>}

export function ModuleSectionActions({ module, section, canManage, lookups }: Props) {
  if (!canManage) return null;
  if (module === 'CRM') return <CrmActions section={section} lookups={lookups} />;
  if (module === 'HRM') return <HrmActions section={section} lookups={lookups} />;
  if (module === 'Projects & Tasks') return <TasklyActions section={section} lookups={lookups} />;
  return null;
}
