<?php

return [
    'php' => [
        'bacon/bacon-qr-code' => '^3.0',
        'google/apiclient' => '^2.18',
        'guzzlehttp/guzzle' => '^7.10',
        'league/oauth2-client' => '^2.8',
        'mailchimp/marketing' => '^3.0',
        'microsoft/microsoft-graph' => '^2.49',
        'phpoffice/phpspreadsheet' => '^5.1',
        'pusher/pusher-php-server' => '^7.2',
        'razorpay/razorpay' => '^2.9',
        'stripe/stripe-php' => '^17.6',
        'twilio/sdk' => '^8.8',
    ],
    'javascript' => [
        '@fullcalendar/daygrid' => '^6.1.19',
        '@fullcalendar/interaction' => '^6.1.19',
        '@fullcalendar/react' => '^6.1.19',
        '@fullcalendar/timegrid' => '^6.1.19',
        '@hello-pangea/dnd' => '^18.0.1',
        '@radix-ui/react-alert-dialog' => '^1.0.5',
        '@radix-ui/react-avatar' => '^1.1.1',
        '@radix-ui/react-checkbox' => '^1.3.3',
        '@radix-ui/react-collapsible' => '^1.1.1',
        '@radix-ui/react-dialog' => '^1.1.14',
        '@radix-ui/react-dropdown-menu' => '^2.1.2',
        '@radix-ui/react-label' => '^2.0.2',
        '@radix-ui/react-popover' => '^1.1.15',
        '@radix-ui/react-radio-group' => '^1.3.8',
        '@radix-ui/react-scroll-area' => '^1.0.5',
        '@radix-ui/react-select' => '^2.2.5',
        '@radix-ui/react-separator' => '^1.1.0',
        '@radix-ui/react-slider' => '^1.3.6',
        '@radix-ui/react-slot' => '^1.1.0',
        '@radix-ui/react-switch' => '^1.2.6',
        '@radix-ui/react-toggle' => '^1.1.10',
        '@radix-ui/react-tooltip' => '^1.1.3',
        '@tiptap/extension-color' => '^3.3.0',
        '@tiptap/extension-highlight' => '^3.3.0',
        '@tiptap/extension-link' => '^3.3.0',
        '@tiptap/extension-strike' => '^3.3.0',
        '@tiptap/extension-text-align' => '^3.3.0',
        '@tiptap/extension-text-style' => '^3.3.0',
        '@tiptap/extension-underline' => '^3.3.0',
        '@tiptap/pm' => '^3.3.0',
        '@tiptap/react' => '^3.3.0',
        '@tiptap/starter-kit' => '^3.3.0',
        '@types/jsbarcode' => '^3.11.1',
        '@types/qrcode' => '^1.5.5',
        '@types/react-google-recaptcha' => '^2.1.9',
        'class-variance-authority' => '^0.7.0',
        'date-fns' => '^3.6.0',
        'html2pdf.js' => '^0.12.1',
        'i18next' => '^25.3.6',
        'i18next-browser-languagedetector' => '^8.2.0',
        'i18next-http-backend' => '^3.0.2',
        'jsbarcode' => '^3.11.6',
        'jspdf' => '^3.0.4',
        'jspdf-autotable' => '^5.0.2',
        'laravel-echo' => '^1.15.3',
        'pusher-js' => '^8.4.0',
        'qrcode' => '^1.5.4',
        'react-datepicker' => '^8.7.0',
        'react-day-picker' => '^9.9.0',
        'react-google-recaptcha' => '^3.1.0',
        'react-i18next' => '^15.6.1',
        'react-signature-canvas' => '^1.0.7',
        'recharts' => '^3.2.0',
        'sonner' => '^2.0.7',
        'tailwindcss-animate' => '^1.0.7',
        'unicode-emoji-json' => '^0.8.0',
    ],
    'excluded' => [
        '@inertiajs/vue3' => 'HiddenLeaf is React, not Vue',
        '@syncfusion/*' => 'requires separate license review',
        'next-themes' => 'reference version does not advertise React 19 peer support',
        '@headlessui/react' => 'reference version targets React <=18; use a React 19-compatible release if needed',
    ],
];
