<?php

return [
    ['module' => 'Account', 'menu_type' => 'company-menu', 'title' => 'Account Dashboard', 'route' => 'account.index', 'permission' => 'manage-account-dashboard', 'parent' => 'dashboard', 'order' => 20],
    ['module' => 'Account', 'menu_type' => 'company-menu', 'title' => 'Accounting', 'route' => 'account.customers.index', 'permission' => 'manage-account', 'group' => 'Accounting & Finance', 'order' => 400],
    ['module' => 'Account', 'menu_type' => 'company-menu', 'title' => 'Customers', 'route' => 'account.customers.index', 'permission' => 'manage-customers'],
    ['module' => 'Account', 'menu_type' => 'company-menu', 'title' => 'Vendors', 'route' => 'account.vendors.index', 'permission' => 'manage-vendors'],
    ['module' => 'Account', 'menu_type' => 'company-menu', 'title' => 'Revenue', 'route' => 'account.revenues.index', 'permission' => 'manage-revenues'],
    ['module' => 'Account', 'menu_type' => 'company-menu', 'title' => 'Expense', 'route' => 'account.expenses.index', 'permission' => 'manage-expenses'],
    ['module' => 'Account', 'menu_type' => 'company-menu', 'title' => 'Banking', 'route' => 'account.bank-accounts.index', 'permission' => 'manage-bank-accounts'],
    ['module' => 'Account', 'menu_type' => 'company-menu', 'title' => 'Bank Accounts', 'route' => 'account.bank-accounts.index', 'permission' => 'manage-bank-accounts'],
    ['module' => 'Account', 'menu_type' => 'company-menu', 'title' => 'Bank Transactions', 'route' => 'account.bank-transactions.index', 'permission' => 'manage-bank-transactions'],
    ['module' => 'Account', 'menu_type' => 'company-menu', 'title' => 'Bank Transfers', 'route' => 'account.bank-transfers.index', 'permission' => 'manage-bank-transfers'],
    ['module' => 'Account', 'menu_type' => 'company-menu', 'title' => 'Customer Payments', 'route' => 'account.customer-payments.index', 'permission' => 'manage-customer-payments'],
    ['module' => 'Account', 'menu_type' => 'company-menu', 'title' => 'Vendor Payments', 'route' => 'account.vendor-payments.index', 'permission' => 'manage-vendor-payments'],
    ['module' => 'Account', 'menu_type' => 'company-menu', 'title' => 'Debit Notes', 'route' => 'account.debit-notes.index', 'permission' => 'manage-debit-notes'],
    ['module' => 'Account', 'menu_type' => 'company-menu', 'title' => 'Credit Notes', 'route' => 'account.credit-notes.index', 'permission' => 'manage-credit-notes'],
    ['module' => 'Account', 'menu_type' => 'company-menu', 'title' => 'Reports', 'route' => 'account.reports.index', 'permission' => 'manage-account-reports'],
    ['module' => 'Account', 'menu_type' => 'company-menu', 'title' => 'Chart Of Accounts', 'route' => 'account.chart-of-accounts.index', 'permission' => 'manage-chart-of-accounts'],
    ['module' => 'Account', 'menu_type' => 'company-menu', 'title' => 'System Setup', 'route' => 'account.account-types.index', 'permission' => 'manage-account-types'],
    ['module' => 'BudgetPlanner', 'menu_type' => 'company-menu', 'title' => 'Budget Planner', 'route' => 'budget-planner.budgets.index', 'permission' => 'manage-budget-planner', 'group' => 'Accounting & Finance', 'order' => 420],
    ['module' => 'BudgetPlanner', 'menu_type' => 'company-menu', 'title' => 'Budget', 'route' => 'budget-planner.budgets.index', 'permission' => 'manage-budgets'],
    ['module' => 'BudgetPlanner', 'menu_type' => 'company-menu', 'title' => 'Budget Monitoring', 'route' => 'budget-planner.budget-monitorings.index', 'permission' => 'manage-budget-monitoring'],
    ['module' => 'BudgetPlanner', 'menu_type' => 'company-menu', 'title' => 'Budget Allocations', 'route' => 'budget-planner.budget-allocations.index', 'permission' => 'manage-budget-allocations'],
    ['module' => 'BudgetPlanner', 'menu_type' => 'company-menu', 'title' => 'Budget Periods', 'route' => 'budget-planner.budget-periods.index', 'permission' => 'manage-budget-periods'],
    ['module' => 'DoubleEntry', 'menu_type' => 'company-menu', 'title' => 'Double Entry', 'route' => 'double-entry.ledger-summary.index', 'permission' => 'manage-double-entry', 'group' => 'Accounting & Finance', 'order' => 425],
    ['module' => 'DoubleEntry', 'menu_type' => 'company-menu', 'title' => 'Ledger Summary', 'route' => 'double-entry.ledger-summary.index', 'permission' => 'manage-ledger-summary', 'order' => 10],
    ['module' => 'DoubleEntry', 'menu_type' => 'company-menu', 'title' => 'Trial Balance', 'route' => 'double-entry.trial-balance.index', 'permission' => 'manage-trial-balance', 'order' => 20],
    ['module' => 'DoubleEntry', 'menu_type' => 'company-menu', 'title' => 'Balance Sheets', 'route' => 'double-entry.balance-sheets.index', 'permission' => 'manage-balance-sheets', 'order' => 30],
    ['module' => 'DoubleEntry', 'menu_type' => 'company-menu', 'title' => 'Profit & Loss', 'route' => 'double-entry.profit-loss.index', 'permission' => 'manage-profit-loss', 'order' => 40],
    ['module' => 'DoubleEntry', 'menu_type' => 'company-menu', 'title' => 'Reports', 'route' => 'double-entry.reports.index', 'permission' => 'manage-double-entry-reports', 'order' => 50],
    ['module' => 'Goal', 'menu_type' => 'company-menu', 'title' => 'Goal', 'route' => 'goal.goals.index', 'permission' => 'manage-goal', 'group' => 'Accounting & Finance', 'order' => 415],
    ['module' => 'Goal', 'menu_type' => 'company-menu', 'title' => 'Goals', 'route' => 'goal.goals.index', 'permission' => 'manage-goals'],
    ['module' => 'Goal', 'menu_type' => 'company-menu', 'title' => 'Milestones', 'route' => 'goal.milestones.index', 'permission' => 'manage-goal-milestones'],
    ['module' => 'Goal', 'menu_type' => 'company-menu', 'title' => 'Tracking', 'route' => 'goal.tracking.index', 'permission' => 'manage-goal-tracking'],
    ['module' => 'Goal', 'menu_type' => 'company-menu', 'title' => 'Contributions', 'route' => 'goal.contributions.index', 'permission' => 'manage-goal-contributions'],
    ['module' => 'Goal', 'menu_type' => 'company-menu', 'title' => 'Category', 'route' => 'goal.categories.index', 'permission' => 'manage-categories'],
];
