<?php

return [
    'source' => 'ERPGo/WorkDo functional reference',
    'modules' => [
        ['name' => 'AIAssistant', 'alias' => 'AI Assistant', 'package_name' => 'aiassistant', 'priority' => 400, 'version' => 5.0],
        ['name' => 'Aamarpay', 'alias' => 'AamarPay', 'package_name' => 'aamarpay', 'priority' => 1640, 'version' => 5.0],
        ['name' => 'Account', 'alias' => 'Accounting', 'package_name' => 'account', 'priority' => 20, 'version' => 5.0, 'child_module' => ['Goal', 'BudgetPlanner', 'DoubleEntry']],
        ['name' => 'AuthorizeNet', 'alias' => 'AuthorizeNet', 'package_name' => 'authorize-net', 'priority' => 1780, 'version' => 5.0],
        ['name' => 'Benefit', 'alias' => 'Benefit', 'package_name' => 'benefit', 'priority' => 1650, 'version' => 5.0],
        ['name' => 'BudgetPlanner', 'alias' => 'Budget Planner', 'package_name' => 'budget-planner', 'priority' => 245, 'version' => 5.0],
        ['name' => 'Calendar', 'alias' => 'Calendar', 'package_name' => 'calendar', 'priority' => 875, 'version' => 5.0],
        ['name' => 'Cashfree', 'alias' => 'Cashfree', 'package_name' => 'cashfree', 'priority' => 1660, 'version' => 5.0],
        ['name' => 'CinetPay', 'alias' => 'CinetPay', 'package_name' => 'cinet-pay', 'priority' => 1820, 'version' => 5.0],
        ['name' => 'Coingate', 'alias' => 'Coingate', 'package_name' => 'coingate', 'priority' => 1670, 'version' => 5.0],
        ['name' => 'Contract', 'alias' => 'Contract', 'package_name' => 'contract', 'priority' => 300, 'version' => 5.0, 'child_module' => ['ContractTemplate']],
        ['name' => 'DoubleEntry', 'alias' => 'Double Entry', 'package_name' => 'double-entry', 'priority' => 220, 'version' => 5.0],
        ['name' => 'Easebuzz', 'alias' => 'Easebuzz', 'package_name' => 'easebuzz', 'priority' => 1890, 'version' => 5.0],
        ['name' => 'Fedapay', 'alias' => 'Fedapay', 'package_name' => 'fedapay', 'priority' => 1810, 'version' => 5.0],
        ['name' => 'Flutterwave', 'alias' => 'Flutterwave', 'package_name' => 'flutterwave', 'priority' => 1520, 'version' => 5.0],
        ['name' => 'FormBuilder', 'alias' => 'Form Builder', 'package_name' => 'form-builder', 'priority' => 280, 'version' => 5.0],
        ['name' => 'Goal', 'alias' => 'Financial Goal', 'package_name' => 'goal', 'priority' => 230, 'version' => 5.0],
        ['name' => 'GoogleCaptcha', 'alias' => 'Google Captcha', 'package_name' => 'google-captcha', 'priority' => 880, 'version' => 5.0],
        ['name' => 'Hrm', 'alias' => 'HRM', 'package_name' => 'hrm', 'priority' => 30, 'version' => 5.0],
        ['name' => 'Iyzipay', 'alias' => 'Iyzipay', 'package_name' => 'iyzipay', 'priority' => 1620, 'version' => 5.0],
        ['name' => 'Khalti', 'alias' => 'Khalti', 'package_name' => 'khalti', 'priority' => 1760, 'version' => 5.0],
        ['name' => 'LandingPage', 'alias' => 'CMS', 'package_name' => 'landing-page', 'priority' => 20, 'version' => 1.0],
        ['name' => 'Lead', 'alias' => 'CRM', 'package_name' => 'lead', 'priority' => 40, 'version' => 5.0],
        ['name' => 'Mercado', 'alias' => 'Mercado', 'package_name' => 'mercado', 'priority' => 1700, 'version' => 5.1],
        ['name' => 'Midtrans', 'alias' => 'Midtrans', 'package_name' => 'midtrans', 'priority' => 1730, 'version' => 5.0],
        ['name' => 'Mollie', 'alias' => 'Mollie', 'package_name' => 'mollie', 'priority' => 1535, 'version' => 5.0],
        ['name' => 'Ozow', 'alias' => 'Ozow', 'package_name' => 'ozow', 'priority' => 1860, 'version' => 5.0],
        ['name' => 'PaiementPro', 'alias' => 'PaiementPro', 'package_name' => 'paiement-pro', 'priority' => 1800, 'version' => 5.0],
        ['name' => 'PayHere', 'alias' => 'PayHere', 'package_name' => 'pay-here', 'priority' => 1790, 'version' => 5.0],
        ['name' => 'PayTR', 'alias' => 'PayTR', 'package_name' => 'pay-tr', 'priority' => 1630, 'version' => 5.0],
        ['name' => 'PayTab', 'alias' => 'PayTabs', 'package_name' => 'pay-tab', 'priority' => 1580, 'version' => 5.0],
        ['name' => 'Payfast', 'alias' => 'Payfast', 'package_name' => 'payfast', 'priority' => 1560, 'version' => 5.0],
        ['name' => 'Paypal', 'alias' => 'Paypal', 'package_name' => 'paypal', 'priority' => 1510, 'version' => 5.0],
        ['name' => 'Paystack', 'alias' => 'Paystack', 'package_name' => 'paystack', 'priority' => 1530, 'version' => 5.0],
        ['name' => 'Performance', 'alias' => 'Performance', 'package_name' => 'performance', 'priority' => 260, 'version' => 5.0],
        ['name' => 'Pos', 'alias' => 'POS', 'package_name' => 'pos', 'priority' => 50, 'version' => 5.0],
        ['name' => 'ProductService', 'alias' => 'Product & Service', 'package_name' => 'product-service', 'priority' => 0, 'version' => 5.0, 'child_module' => ['HubSpot']],
        ['name' => 'Quotation', 'alias' => 'Quotation', 'package_name' => 'quotation', 'priority' => 320, 'version' => 5.0],
        ['name' => 'Razorpay', 'alias' => 'Razorpay', 'package_name' => 'razorpay', 'priority' => 1540, 'version' => 5.0],
        ['name' => 'Recruitment', 'alias' => 'Recruitment', 'package_name' => 'recruitment', 'priority' => 270, 'version' => 5.0, 'child_module' => ['JobSearch']],
        ['name' => 'Slack', 'alias' => 'Slack', 'package_name' => 'slack', 'priority' => 750, 'version' => 5.0],
        ['name' => 'Stripe', 'alias' => 'Stripe', 'package_name' => 'stripe', 'priority' => 1500, 'version' => 5.0],
        ['name' => 'SupportTicket', 'alias' => 'Support Ticket', 'package_name' => 'support-ticket', 'priority' => 130, 'version' => 5.0],
        ['name' => 'Tap', 'alias' => 'Tap', 'package_name' => 'tap', 'priority' => 1750, 'version' => 5.0],
        ['name' => 'Taskly', 'alias' => 'Project', 'package_name' => 'taskly', 'priority' => 10, 'version' => 5.0],
        ['name' => 'Telegram', 'alias' => 'Telegram', 'package_name' => 'telegram', 'priority' => 760, 'version' => 5.0],
        ['name' => 'Timesheet', 'alias' => 'Timesheet', 'package_name' => 'timesheet', 'priority' => 310, 'version' => 5.0],
        ['name' => 'Toyyibpay', 'alias' => 'Toyyibpay', 'package_name' => 'toyyibpay', 'priority' => 1600, 'version' => 5.0],
        ['name' => 'Training', 'alias' => 'Training', 'package_name' => 'training', 'priority' => 250, 'version' => 5.0],
        ['name' => 'Twilio', 'alias' => 'Twilio', 'package_name' => 'twilio', 'priority' => 770, 'version' => 5.0],
        ['name' => 'Webhook', 'alias' => 'Webhook', 'package_name' => 'webhook', 'priority' => 930, 'version' => 5.0],
        ['name' => 'Xendit', 'alias' => 'Xendit', 'package_name' => 'xendit', 'priority' => 1740, 'version' => 5.0],
        ['name' => 'YooKassa', 'alias' => 'YooKassa', 'package_name' => 'yoo-kassa', 'priority' => 1570, 'version' => 5.0],
        ['name' => 'ZoomMeeting', 'alias' => 'Zoom Meeting', 'package_name' => 'zoom-meeting', 'priority' => 900, 'version' => 5.0],
    ],
    'role_presets' => [
        'staff' => [
            'label' => 'Staff',
            'editable' => false,
            'permissions' => [
                'manage-dashboard','manage-media','manage-own-media','create-media','download-media','delete-media','manage-media-directories','manage-own-media-directories','create-media-directories','edit-media-directories','delete-media-directories','manage-profile','edit-profile','change-password-profile','manage-messenger','send-messages','view-messages','toggle-favorite-messages','toggle-pinned-messages',
            ],
        ],
        'client' => [
            'label' => 'Client',
            'editable' => false,
            'permissions' => [
                'manage-dashboard','manage-media','manage-own-media','create-media','download-media','delete-media','manage-media-directories','manage-own-media-directories','create-media-directories','edit-media-directories','delete-media-directories','manage-profile','edit-profile','change-password-profile','manage-messenger','send-messages','view-messages','toggle-favorite-messages','toggle-pinned-messages','manage-sales-invoices','manage-own-sales-invoices','view-sales-invoices','print-sales-invoices','manage-sales-return-invoices','manage-own-sales-return-invoices','view-sales-return-invoices','manage-sales-proposals','manage-own-sales-proposals','view-sales-proposals','print-sales-proposals','accept-sales-proposals','reject-sales-proposals',
            ],
        ],
        'vendor' => [
            'label' => 'Vendor',
            'editable' => false,
            'permissions' => [
                'manage-dashboard','manage-media','manage-own-media','create-media','download-media','delete-media','manage-media-directories','manage-own-media-directories','create-media-directories','edit-media-directories','delete-media-directories','manage-profile','edit-profile','change-password-profile','manage-messenger','send-messages','view-messages','toggle-favorite-messages','toggle-pinned-messages','manage-purchase-invoices','manage-own-purchase-invoices','view-purchase-invoices','print-purchase-invoices','manage-purchase-return-invoices','manage-own-purchase-return-invoices','view-purchase-return-invoices',
            ],
        ],
    ],
];
