<?php

return [
    ['module' => 'Contract', 'menu_type' => 'company-menu', 'title' => 'Contract', 'route' => 'contract.index', 'permission' => 'manage-contracts', 'group' => 'Sales & Revenue', 'order' => 725],
    ['module' => 'Contract', 'menu_type' => 'company-menu', 'title' => 'Contracts', 'route' => 'contract.index', 'permission' => 'manage-contracts', 'order' => 10],
    ['module' => 'Contract', 'menu_type' => 'company-menu', 'title' => 'Contract Types', 'route' => 'contract-types.index', 'permission' => 'manage-contract-types', 'order' => 30],
    ['module' => 'LandingPage', 'menu_type' => 'superadmin-menu', 'title' => 'CMS', 'route' => 'landing-page.index', 'permission' => 'manage-landing-page', 'group' => 'Content & Pages', 'order' => 35],
    ['module' => 'LandingPage', 'menu_type' => 'superadmin-menu', 'title' => 'Landing Page', 'route' => 'landing-page.index', 'permission' => 'manage-landing-page', 'order' => 1],
    ['module' => 'LandingPage', 'menu_type' => 'superadmin-menu', 'title' => 'Marketplace', 'route' => 'marketplace.settings', 'permission' => 'manage-marketplace-settings', 'order' => 2],
    ['module' => 'LandingPage', 'menu_type' => 'superadmin-menu', 'title' => 'Custom Pages', 'route' => 'custom-pages.index', 'permission' => 'manage-custom-pages', 'order' => 3],
    ['module' => 'LandingPage', 'menu_type' => 'superadmin-menu', 'title' => 'Newsletter Subscribers', 'route' => 'newsletter-subscribers.index', 'permission' => 'manage-newsletter-subscribers', 'order' => 4],
    ['module' => 'Pos', 'menu_type' => 'company-menu', 'title' => 'POS Dashboard', 'route' => 'pos.index', 'permission' => 'manage-pos-dashboard', 'parent' => 'dashboard', 'order' => 40],
    ['module' => 'Pos', 'menu_type' => 'company-menu', 'title' => 'POS', 'route' => 'pos.create', 'permission' => 'manage-pos', 'group' => 'Purchase & Inventory', 'order' => 475],
    ['module' => 'Pos', 'menu_type' => 'company-menu', 'title' => 'Add POS', 'route' => 'pos.create', 'permission' => 'create-pos'],
    ['module' => 'Pos', 'menu_type' => 'company-menu', 'title' => 'POS Orders', 'route' => 'pos.orders', 'permission' => 'manage-pos-orders'],
    ['module' => 'Pos', 'menu_type' => 'company-menu', 'title' => 'Print Barcode', 'route' => 'pos.barcode', 'permission' => 'manage-pos-barcodes'],
    ['module' => 'Pos', 'menu_type' => 'company-menu', 'title' => 'Reports', 'route' => 'pos.reports.sales', 'permission' => 'manage-pos-reports'],
    ['module' => 'Pos', 'menu_type' => 'company-menu', 'title' => 'Sales Report', 'route' => 'pos.reports.sales', 'permission' => 'view-pos-reports'],
    ['module' => 'Pos', 'menu_type' => 'company-menu', 'title' => 'Product Report', 'route' => 'pos.reports.products', 'permission' => 'view-pos-reports'],
    ['module' => 'Pos', 'menu_type' => 'company-menu', 'title' => 'Customer Report', 'route' => 'pos.reports.customers', 'permission' => 'view-pos-reports'],
    ['module' => 'ProductService', 'menu_type' => 'company-menu', 'title' => 'Product & Service', 'route' => 'product-service.items.index', 'permission' => 'manage-product-service-item', 'group' => 'Purchase & Inventory', 'order' => 470],
    ['module' => 'ProductService', 'menu_type' => 'company-menu', 'title' => 'Items', 'route' => 'product-service.items.index', 'permission' => 'manage-product-service-item'],
    ['module' => 'ProductService', 'menu_type' => 'company-menu', 'title' => 'System Setup', 'route' => 'product-service.item-categories.index', 'permission' => 'manage-product-service-item'],
    ['module' => 'Quotation', 'menu_type' => 'company-menu', 'title' => 'Quotation', 'route' => 'quotations.index', 'permission' => 'manage-quotations', 'group' => 'Sales & Revenue', 'order' => 260],
    ['module' => 'SupportTicket', 'menu_type' => 'company-menu', 'title' => 'Support Dashboard', 'route' => 'dashboard.support-tickets', 'permission' => 'manage-support-tickets', 'parent' => 'dashboard', 'order' => 140],
    ['module' => 'SupportTicket', 'menu_type' => 'company-menu', 'title' => 'Support Ticket', 'route' => 'support-tickets.index', 'permission' => 'manage-support-tickets', 'group' => 'Support & Communication', 'order' => 700],
    ['module' => 'SupportTicket', 'menu_type' => 'company-menu', 'title' => 'Tickets', 'route' => 'support-tickets.index', 'permission' => 'manage-support-tickets'],
    ['module' => 'SupportTicket', 'menu_type' => 'company-menu', 'title' => 'Knowledge Base', 'route' => 'support-ticket-knowledge.index', 'permission' => 'manage-knowledge-base'],
    ['module' => 'SupportTicket', 'menu_type' => 'company-menu', 'title' => 'FAQ', 'route' => 'support-ticket-faq.index', 'permission' => 'manage-faq'],
    ['module' => 'SupportTicket', 'menu_type' => 'company-menu', 'title' => 'Contact', 'route' => 'support-ticket-contact.index', 'permission' => 'manage-contact'],
    ['module' => 'SupportTicket', 'menu_type' => 'company-menu', 'title' => 'System Setup', 'route' => 'ticket-category.index', 'permission' => 'manage-ticket-categories'],
    ['module' => 'ZoomMeeting', 'menu_type' => 'company-menu', 'title' => 'Zoom Meetings', 'route' => 'zoommeeting.zoom-meetings.index', 'permission' => 'manage-zoom-meetings', 'group' => 'Project Management', 'order' => 950],
];
