<?php

return [
    ['module' => 'Hrm', 'menu_type' => 'company-menu', 'title' => 'HRM Dashboard', 'route' => 'hrm.index', 'permission' => 'manage-hrm-dashboard', 'parent' => 'dashboard', 'order' => 30],
    ['module' => 'Hrm', 'menu_type' => 'company-menu', 'title' => 'HRM', 'route' => 'hrm.employees.index', 'permission' => 'manage-hrm', 'group' => 'HR Management', 'order' => 450],
    ['module' => 'Hrm', 'menu_type' => 'company-menu', 'title' => 'Employees', 'route' => 'hrm.employees.index', 'permission' => 'manage-employees'],
    ['module' => 'Hrm', 'menu_type' => 'company-menu', 'title' => 'Attendance', 'route' => 'hrm.attendances.index', 'permission' => 'manage-attendances'],
    ['module' => 'Hrm', 'menu_type' => 'company-menu', 'title' => 'Attendances', 'route' => 'hrm.attendances.index', 'permission' => 'manage-attendances'],
    ['module' => 'Hrm', 'menu_type' => 'company-menu', 'title' => 'Shifts', 'route' => 'hrm.shifts.index', 'permission' => 'manage-shifts'],
    ['module' => 'Hrm', 'menu_type' => 'company-menu', 'title' => 'Leave Management', 'route' => 'hrm.leave-applications.index', 'permission' => 'manage-leave-applications'],
    ['module' => 'Hrm', 'menu_type' => 'company-menu', 'title' => 'Leave Applications', 'route' => 'hrm.leave-applications.index', 'permission' => 'manage-leave-applications'],
    ['module' => 'Hrm', 'menu_type' => 'company-menu', 'title' => 'Leave Balance', 'route' => 'hrm.leave-balance.index', 'permission' => 'manage-leave-balance'],
    ['module' => 'Hrm', 'menu_type' => 'company-menu', 'title' => 'Leave Types', 'route' => 'hrm.leave-types.index', 'permission' => 'manage-leave-types'],
    ['module' => 'Hrm', 'menu_type' => 'company-menu', 'title' => 'Payslip', 'route' => 'hrm.payrolls.index', 'permission' => 'manage-payrolls'],
    ['module' => 'Hrm', 'menu_type' => 'company-menu', 'title' => 'Payroll', 'route' => 'hrm.payrolls.index', 'permission' => 'manage-payrolls'],
    ['module' => 'Hrm', 'menu_type' => 'company-menu', 'title' => 'Set Salary', 'route' => 'hrm.set-salary.index', 'permission' => 'manage-set-salary'],
    ['module' => 'Hrm', 'menu_type' => 'company-menu', 'title' => 'Holidays', 'route' => 'hrm.holidays.index', 'permission' => 'manage-holidays'],
    ['module' => 'Hrm', 'menu_type' => 'company-menu', 'title' => 'Announcements', 'route' => 'hrm.announcements.index', 'permission' => 'manage-announcements'],
    ['module' => 'Hrm', 'menu_type' => 'company-menu', 'title' => 'Events', 'route' => 'hrm.events.index', 'permission' => 'manage-events'],
    ['module' => 'Hrm', 'menu_type' => 'company-menu', 'title' => 'Documents', 'route' => 'hrm.documents.index', 'permission' => 'manage-hrm-documents'],
    ['module' => 'Hrm', 'menu_type' => 'company-menu', 'title' => 'Acknowledgments', 'route' => 'hrm.acknowledgments.index', 'permission' => 'manage-acknowledgments'],
    ['module' => 'Hrm', 'menu_type' => 'company-menu', 'title' => 'Awards', 'route' => 'hrm.awards.index', 'permission' => 'manage-awards'],
    ['module' => 'Hrm', 'menu_type' => 'company-menu', 'title' => 'Promotions', 'route' => 'hrm.promotions.index', 'permission' => 'manage-promotions'],
    ['module' => 'Hrm', 'menu_type' => 'company-menu', 'title' => 'Transfers', 'route' => 'hrm.employee-transfers.index', 'permission' => 'manage-employee-transfers'],
    ['module' => 'Hrm', 'menu_type' => 'company-menu', 'title' => 'Warnings', 'route' => 'hrm.warnings.index', 'permission' => 'manage-warnings'],
    ['module' => 'Hrm', 'menu_type' => 'company-menu', 'title' => 'Complaints', 'route' => 'hrm.complaints.index', 'permission' => 'manage-complaints'],
    ['module' => 'Hrm', 'menu_type' => 'company-menu', 'title' => 'Resignations', 'route' => 'hrm.resignations.index', 'permission' => 'manage-resignations'],
    ['module' => 'Hrm', 'menu_type' => 'company-menu', 'title' => 'Terminations', 'route' => 'hrm.terminations.index', 'permission' => 'manage-terminations'],
    ['module' => 'Hrm', 'menu_type' => 'company-menu', 'title' => 'System Setup', 'route' => 'hrm.branches.index', 'permission' => 'manage-hrm'],
    ['module' => 'Performance', 'menu_type' => 'company-menu', 'title' => 'Performance', 'route' => 'performance.employee-reviews.index', 'permission' => 'manage-performance', 'group' => 'HR Management', 'order' => 451],
    ['module' => 'Performance', 'menu_type' => 'company-menu', 'title' => 'Employee Reviews', 'route' => 'performance.employee-reviews.index', 'permission' => 'manage-employee-reviews'],
    ['module' => 'Performance', 'menu_type' => 'company-menu', 'title' => 'Employee Goals', 'route' => 'performance.employee-goals.index', 'permission' => 'manage-employee-goals'],
    ['module' => 'Performance', 'menu_type' => 'company-menu', 'title' => 'Review Cycles', 'route' => 'performance.review-cycles.index', 'permission' => 'manage-review-cycles'],
    ['module' => 'Performance', 'menu_type' => 'company-menu', 'title' => 'Performance Indicators', 'route' => 'performance.indicators.index', 'permission' => 'manage-performance-indicators'],
    ['module' => 'Performance', 'menu_type' => 'company-menu', 'title' => 'System Setup', 'route' => 'performance.indicator-categories.index', 'permission' => 'manage-performance-system-setup'],
    ['module' => 'Recruitment', 'menu_type' => 'company-menu', 'title' => 'Recruitment Dashboard', 'route' => 'recruitment.index', 'permission' => 'manage-recruitment-dashboard', 'parent' => 'dashboard', 'order' => 35],
    ['module' => 'Recruitment', 'menu_type' => 'company-menu', 'title' => 'Recruitment', 'route' => 'recruitment.job-postings.index', 'permission' => 'manage-recruitment', 'group' => 'HR Management', 'order' => 453],
    ['module' => 'Recruitment', 'menu_type' => 'company-menu', 'title' => 'Job Postings', 'route' => 'recruitment.job-postings.index', 'permission' => 'manage-job-postings'],
    ['module' => 'Recruitment', 'menu_type' => 'company-menu', 'title' => 'Candidates', 'route' => 'recruitment.candidates.index', 'permission' => 'manage-candidates'],
    ['module' => 'Recruitment', 'menu_type' => 'company-menu', 'title' => 'Interviews', 'route' => 'recruitment.interviews.index', 'permission' => 'manage-interviews'],
    ['module' => 'Recruitment', 'menu_type' => 'company-menu', 'title' => 'Interview Feedback', 'route' => 'recruitment.interview-feedbacks.index', 'permission' => 'manage-interview-feedbacks'],
    ['module' => 'Recruitment', 'menu_type' => 'company-menu', 'title' => 'Candidate Assessments', 'route' => 'recruitment.candidate-assessments.index', 'permission' => 'manage-candidate-assessments'],
    ['module' => 'Recruitment', 'menu_type' => 'company-menu', 'title' => 'Offers', 'route' => 'recruitment.offers.index', 'permission' => 'manage-offers'],
    ['module' => 'Recruitment', 'menu_type' => 'company-menu', 'title' => 'Candidate Onboarding', 'route' => 'recruitment.candidate-onboardings.index', 'permission' => 'manage-candidate-onboardings'],
    ['module' => 'Recruitment', 'menu_type' => 'company-menu', 'title' => 'Interview Rounds', 'route' => 'recruitment.interview-rounds.index', 'permission' => 'manage-interview-rounds'],
    ['module' => 'Recruitment', 'menu_type' => 'company-menu', 'title' => 'Checklist Items', 'route' => 'recruitment.checklist-items.index', 'permission' => 'manage-checklist-items'],
    ['module' => 'Recruitment', 'menu_type' => 'company-menu', 'title' => 'Job Locations', 'route' => 'recruitment.job-locations.index', 'permission' => 'manage-job-locations'],
    ['module' => 'Recruitment', 'menu_type' => 'company-menu', 'title' => 'Custom Questions', 'route' => 'recruitment.custom-questions.index', 'permission' => 'manage-custom-questions'],
    ['module' => 'Recruitment', 'menu_type' => 'company-menu', 'title' => 'System Setup', 'route' => 'recruitment.job-types.index', 'permission' => 'manage-recruitment-system-setup'],
    ['module' => 'Training', 'menu_type' => 'company-menu', 'title' => 'Training', 'route' => 'training.trainings.index', 'permission' => 'manage-training', 'group' => 'HR Management', 'order' => 452],
    ['module' => 'Training', 'menu_type' => 'company-menu', 'title' => 'Training List', 'route' => 'training.trainings.index', 'permission' => 'manage-trainings'],
    ['module' => 'Training', 'menu_type' => 'company-menu', 'title' => 'Trainers', 'route' => 'training.trainers.index', 'permission' => 'manage-trainers'],
    ['module' => 'Training', 'menu_type' => 'company-menu', 'title' => 'Training Types', 'route' => 'training.training-types.index', 'permission' => 'manage-training-types'],
];
