import React, { useMemo, useState } from 'react';
import { Link, router } from '@inertiajs/react';
import AppShell from '@/Layouts/AppShell';
import { Badge } from '@/Components/UI/Badge';
import { Button } from '@/Components/UI/Button';
import { Card } from '@/Components/UI/Card';
import { Input } from '@/Components/UI/Input';
import { Select } from '@/Components/UI/Select';
import { SectionHeader } from '@/Components/UI/SectionHeader';

export default function Manage({ sites = [], marketplaceItems = [], subscribers = [] }: any) {
  const [selectedId, setSelectedId] = useState<number | null>(sites[0]?.id ?? null);
  const selected = useMemo(() => sites.find((site: any) => site.id === selectedId) || sites[0], [sites, selectedId]);
  const [site, setSite] = useState({ name: '', slug: '', title: '', description: '', seo_title: '', seo_description: '', seo_keywords: [] as string[], locale: 'en' });
  const [section, setSection] = useState({ type: 'hero', heading: '', subheading: '', content: {} as any, position: 0, is_visible: true });
  const [page, setPage] = useState({ slug: '', title: '', content: '', seo_title: '', seo_description: '', is_published: false, position: 0 });
  const [market, setMarket] = useState({ name: '', description: '', url: '', position: 0, is_visible: true });
  const [subscriber, setSubscriber] = useState({ name: '', email: '' });
  return <AppShell title="Landing Page CMS" breadcrumbs={[{ label: 'CMS' }, { label: 'Landing Page' }]}><div className="space-y-6"><SectionHeader title="Landing Page & Marketplace CMS" description="Manage public sites, ordered sections, custom pages, SEO, marketplace entries, publishing, and newsletter subscribers." badge={<Badge variant="purple" size="sm">{sites.length} Sites</Badge>} />
    <div className="grid xl:grid-cols-[1fr_2fr] gap-5"><Card level={0} className="p-5"><h3 className="font-bold mb-4">Create Landing Site</h3><form onSubmit={e => { e.preventDefault(); router.post('/landing/sites', site); }} className="space-y-3"><Input label="Internal Name" value={site.name} onChange={e => setSite({ ...site, name: e.target.value })} required /><Input label="Public Slug" value={site.slug} onChange={e => setSite({ ...site, slug: e.target.value })} required /><Input label="Site Title" value={site.title} onChange={e => setSite({ ...site, title: e.target.value })} required /><Input label="Description" value={site.description} onChange={e => setSite({ ...site, description: e.target.value })} /><Input label="SEO Title" value={site.seo_title} onChange={e => setSite({ ...site, seo_title: e.target.value })} /><Input label="SEO Description" value={site.seo_description} onChange={e => setSite({ ...site, seo_description: e.target.value })} /><Input label="Locale" value={site.locale} onChange={e => setSite({ ...site, locale: e.target.value })} required /><Button type="submit" variant="primary">Create Site</Button></form></Card>
      <Card level={0} className="p-5"><div className="flex flex-wrap items-center gap-2 mb-5">{sites.map((item: any) => <button key={item.id} className={`px-3 py-2 rounded-lg text-xs border ${selected?.id === item.id ? 'border-purple-500 text-purple-300' : 'border-[var(--border-subtle)]'}`} onClick={() => setSelectedId(item.id)}>{item.name}</button>)}</div>{selected ? <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-bold">{selected.title}</h3><p className="text-xs text-[var(--text-tertiary)]">/site/{selected.slug} • {selected.locale}</p></div><div className="flex gap-2"><Link href={`/site/${selected.slug}`}><Button variant="secondary" size="sm">Preview</Button></Link><Button variant={selected.is_published ? 'ghost' : 'primary'} size="sm" onClick={() => router.post(`/landing/sites/${selected.id}/publish`, { published: !selected.is_published })}>{selected.is_published ? 'Unpublish' : 'Publish'}</Button><Button variant="danger" size="sm" onClick={() => confirm('Delete this site and all pages?') && router.delete(`/landing/sites/${selected.id}`)}>Delete</Button></div></div>
        <div className="grid lg:grid-cols-2 gap-5"><form onSubmit={e => { e.preventDefault(); router.post(`/landing/sites/${selected.id}/sections`, section); }} className="p-4 rounded-xl border border-[var(--border-subtle)] grid sm:grid-cols-2 gap-3"><h4 className="font-semibold sm:col-span-2">Section Editor</h4><Select label="Type" value={section.type} onChange={e => setSection({ ...section, type: e.target.value })}><option value="hero">Hero</option><option value="features">Features</option><option value="pricing">Pricing</option><option value="testimonials">Testimonials</option><option value="faq">FAQ</option><option value="cta">CTA</option><option value="custom">Custom</option></Select><Input label="Position" type="number" min="0" value={section.position} onChange={e => setSection({ ...section, position: Number(e.target.value) })} /><Input label="Heading" value={section.heading} onChange={e => setSection({ ...section, heading: e.target.value })} /><Input label="Subheading" value={section.subheading} onChange={e => setSection({ ...section, subheading: e.target.value })} /><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={section.is_visible} onChange={e => setSection({ ...section, is_visible: e.target.checked })} /> Visible</label><Button type="submit" variant="primary">Save Section</Button></form>
          <form onSubmit={e => { e.preventDefault(); router.post(`/landing/sites/${selected.id}/pages`, page); }} className="p-4 rounded-xl border border-[var(--border-subtle)] grid sm:grid-cols-2 gap-3"><h4 className="font-semibold sm:col-span-2">Custom Page Editor</h4><Input label="Slug" value={page.slug} onChange={e => setPage({ ...page, slug: e.target.value })} required /><Input label="Title" value={page.title} onChange={e => setPage({ ...page, title: e.target.value })} required /><div className="sm:col-span-2"><Input label="Page Content" value={page.content} onChange={e => setPage({ ...page, content: e.target.value })} required /></div><Input label="SEO Title" value={page.seo_title} onChange={e => setPage({ ...page, seo_title: e.target.value })} /><Input label="SEO Description" value={page.seo_description} onChange={e => setPage({ ...page, seo_description: e.target.value })} /><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={page.is_published} onChange={e => setPage({ ...page, is_published: e.target.checked })} /> Published</label><Button type="submit" variant="primary">Save Page</Button></form></div>
        <EditorRecords site={selected} />
      </div> : <p className="text-sm text-[var(--text-tertiary)]">Create a site to begin editing.</p>}</Card></div>
    <div className="grid xl:grid-cols-2 gap-5"><Card level={0} className="p-5"><h3 className="font-bold mb-4">Marketplace</h3><form onSubmit={e => { e.preventDefault(); router.post('/landing/marketplace', market); }} className="grid sm:grid-cols-2 gap-3"><Input label="Name" value={market.name} onChange={e => setMarket({ ...market, name: e.target.value })} required /><Input label="URL" type="url" value={market.url} onChange={e => setMarket({ ...market, url: e.target.value })} /><Input label="Description" value={market.description} onChange={e => setMarket({ ...market, description: e.target.value })} /><Input label="Position" type="number" value={market.position} onChange={e => setMarket({ ...market, position: Number(e.target.value) })} /><Button type="submit" variant="primary">Add Marketplace Item</Button></form><RecordRows records={marketplaceItems} onRemove={(id: number) => router.delete(`/landing/marketplace/${id}`)} /></Card>
      <Card level={0} className="p-5"><h3 className="font-bold mb-4">Newsletter Subscribers</h3><form onSubmit={e => { e.preventDefault(); router.post('/landing/subscribers', subscriber); }} className="grid sm:grid-cols-2 gap-3"><Input label="Name" value={subscriber.name} onChange={e => setSubscriber({ ...subscriber, name: e.target.value })} /><Input label="Email" type="email" value={subscriber.email} onChange={e => setSubscriber({ ...subscriber, email: e.target.value })} required /><Button type="submit" variant="primary">Add Subscriber</Button></form><div className="mt-4 space-y-2">{subscribers.map((item: any) => <div key={item.id} className="flex items-center justify-between p-3 rounded-xl border border-[var(--border-subtle)]"><div><p className="text-sm font-semibold">{item.name || item.email}</p><p className="text-xs text-[var(--text-tertiary)]">{item.email} • {item.status}</p></div>{item.status === 'subscribed' && <Button size="sm" variant="ghost" onClick={() => router.post(`/landing/subscribers/${item.id}/unsubscribe`)}>Unsubscribe</Button>}</div>)}</div></Card></div>
  </div></AppShell>;
}

function EditorRecords({ site }: any) { return <div className="grid lg:grid-cols-2 gap-4"><RecordRows records={site.sections || []} label={(item: any) => `${item.position}. ${item.type}: ${item.heading || 'Untitled'}`} onRemove={(id: number) => router.delete(`/landing/sites/${site.id}/sections/${id}`)} /><RecordRows records={site.pages || []} label={(item: any) => `${item.title} /${item.slug}`} onRemove={(id: number) => router.delete(`/landing/sites/${site.id}/pages/${id}`)} /></div>; }
function RecordRows({ records, onRemove, label }: any) { return <div className="mt-4 space-y-2">{records.map((item: any) => <div key={item.id} className="flex items-center justify-between p-3 rounded-xl border border-[var(--border-subtle)]"><span className="text-xs font-semibold">{label ? label(item) : item.name}</span><Button size="sm" variant="ghost" onClick={() => onRemove(item.id)}>Remove</Button></div>)}</div>; }
