import React, { useState } from 'react';
import { Head, router } from '@inertiajs/react';
import AppShell from '@/Layouts/AppShell';
import { Card } from '@/Components/UI/Card';
import { Button } from '@/Components/UI/Button';

export default function BankTransfers({transfers,accounts}:{transfers:{data:Array<any>};accounts:Array<any>}) {
  const [form,setForm]=useState({from_account_id:'',to_account_id:'',amount:'',transfer_charges:'0.00',transfer_date:new Date().toISOString().slice(0,10),reference:'',description:''});
  const submit=(e:React.FormEvent)=>{e.preventDefault();router.post('/accounting/bank-transfer-drafts',form,{onSuccess:()=>setForm({...form,amount:'',transfer_charges:'0.00',reference:'',description:''})})};
  return <AppShell><Head title="Accounting — Bank Transfers"/><div className="max-w-7xl mx-auto space-y-6 pb-12">
    <div><h1 className="text-2xl font-bold text-[var(--text-primary)]">Bank Transfers</h1><p className="text-xs text-[var(--text-secondary)] mt-1">Prepare pending transfers, validate source balance, account for bank charges, then process atomically.</p></div>
    <Card level={0} className="p-5"><form onSubmit={submit} className="grid md:grid-cols-6 gap-3"><select required value={form.from_account_id} onChange={e=>setForm({...form,from_account_id:e.target.value})} className="input-shell"><option value="">From account</option>{accounts.map((a:any)=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select><select required value={form.to_account_id} onChange={e=>setForm({...form,to_account_id:e.target.value})} className="input-shell"><option value="">To account</option>{accounts.map((a:any)=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select><input required type="number" min="0.01" step="0.01" placeholder="Amount" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} className="input-shell"/><input type="number" min="0" step="0.01" placeholder="Charges" value={form.transfer_charges} onChange={e=>setForm({...form,transfer_charges:e.target.value})} className="input-shell"/><input required type="date" value={form.transfer_date} onChange={e=>setForm({...form,transfer_date:e.target.value})} className="input-shell"/><Button type="submit" variant="primary">Create Pending</Button><input placeholder="Reference" value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})} className="input-shell md:col-span-2"/><input placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className="input-shell md:col-span-4"/></form></Card>
    <Card level={0} className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr className="text-left border-b border-[var(--border-subtle)]"><th className="p-4">Transfer</th><th>Date</th><th>From</th><th>To</th><th>Amount</th><th>Charges</th><th>Reference</th><th>Status</th><th className="pr-4">Actions</th></tr></thead><tbody>{transfers.data.map((t:any)=><tr key={t.id} className="border-b border-[var(--border-subtle)]"><td className="p-4">{t.transfer_number ?? `#${t.id}`}</td><td>{t.transfer_date}</td><td>{t.from_account?.name ?? t.fromAccount?.name ?? t.from_account_id}</td><td>{t.to_account?.name ?? t.toAccount?.name ?? t.to_account_id}</td><td>{t.amount}</td><td>{t.transfer_charges ?? '0.00'}</td><td>{t.reference ?? '—'}</td><td className="capitalize">{t.status}</td><td className="pr-4 space-x-2">{['pending','draft'].includes(t.status) && <><button className="text-emerald-400" onClick={()=>router.post(`/accounting/bank-transfers/${t.id}/process`)}>Process</button><button className="text-red-400" onClick={()=>router.delete(`/accounting/bank-transfers/${t.id}`)}>Delete</button></>}</td></tr>)}</tbody></table></div></Card>
  </div></AppShell>;
}
